version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5434:5434"
    environment:
      POSTGRES_PASSWORD: password

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.local

  redis:
    image: redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    env_file:
      - .env.local
    depends_on:
      - redis
